/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/lastfm/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lastfm Start
         * @description Send the user to Last.fm to approve us, remembering the request token.
         *
         *     The token is kept in a short-lived signed cookie so the approval can be
         *     completed on the user's return even if Last.fm never calls us back.
         */
        get: operations["lastfm_start_auth_lastfm_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/lastfm/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lastfm Callback
         * @description Trade the approved token for a session and sign the user in.
         *
         *     Uses the token Last.fm hands back, falling back to the one we stashed at
         *     the start of the flow — a user who returns by any route still lands signed in.
         */
        get: operations["lastfm_callback_auth_lastfm_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/lastfm/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lastfm Complete
         * @description Finish a connection whose callback never arrived.
         *
         *     Last.fm only redirects back when the API account has a Callback URL
         *     registered; without one it shows its own success page and leaves the user
         *     to navigate back. The approved token is still redeemable, so this closes
         *     the loop from the app side.
         */
        post: operations["lastfm_complete_auth_lastfm_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Forget the browser. The stored Last.fm session key is left intact so
         *     reconnecting doesn't need another round trip to Last.fm.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Setlists */
        get: operations["list_setlists_setlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setlists/{setlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Setlist */
        get: operations["get_setlist_setlists__setlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setlists/{setlist_id}/cues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Setlist Cues
         * @description Cue windows: which track is playing when, and under what name.
         *
         *     The client reports the player's duration; everything else is derived here so
         *     the highlight and the scrobbler can never disagree about what's playing.
         */
        get: operations["setlist_cues_setlists__setlist_id__cues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setlists/{setlist_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Preview
         * @description Dry-run preview: the ordered add-list + skip report for a target platform.
         *
         *     Network-free (uses exporter.collect.build_plan). Actual playlist creation
         *     needs a connected account and lands with the export phase.
         */
        post: operations["export_preview_setlists__setlist_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CueWindow
         * @description One track's slice of the recording, plus how to name it.
         */
        CueWindow: {
            /** Position */
            position: number;
            /** Component Index */
            component_index?: number | null;
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /**
             * Timing
             * @enum {string}
             */
            timing: "cue" | "estimated";
            /** Label */
            label: string;
            /** Scrobble Artist */
            scrobble_artist?: string | null;
            /** Scrobble Track */
            scrobble_track?: string | null;
            /**
             * Canonical
             * @default false
             */
            canonical: boolean;
            /**
             * Eligible
             * @default true
             */
            eligible: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ExportPlanItem */
        ExportPlanItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /**
         * ExportPreview
         * @description Dry-run export plan: what would be added / skipped, per target platform.
         */
        ExportPreview: {
            /** Target */
            target: string;
            /** Added */
            added: number;
            /** Total Considered */
            total_considered: number;
            /** Items */
            items: components["schemas"]["ExportPlanItem"][];
            /** Skipped */
            skipped: components["schemas"]["ExportSkippedItem"][];
        };
        /** ExportPreviewRequest */
        ExportPreviewRequest: {
            /**
             * Target
             * @enum {string}
             */
            target: "spotify" | "youtube";
            /**
             * Expand Mashups
             * @default true
             */
            expand_mashups: boolean;
            /**
             * Skip Played With
             * @default false
             */
            skip_played_with: boolean;
        };
        /** ExportSkippedItem */
        ExportSkippedItem: {
            /** Label */
            label: string;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LastfmMatch
         * @description The canonical Last.fm identity — these exact strings are the future
         *     scrobble payload (Last.fm's highest-scrobbled entry, typically 1 artist).
         */
        LastfmMatch: {
            /** Artist */
            artist: string;
            /** Track */
            track: string;
            /** Mbid */
            mbid?: string | null;
            /**
             * Listeners
             * @default 0
             */
            listeners: number;
            /** Url */
            url?: string | null;
        };
        /**
         * MashupComponent
         * @description One component track of a mashup.
         */
        MashupComponent: {
            /** Artists */
            artists?: string[];
            /** Title */
            title?: string | null;
            /** Remix */
            remix?: string | null;
            resolution?: components["schemas"]["Resolution"] | null;
        };
        /** Me */
        Me: {
            /** Lastfm Username */
            lastfm_username?: string | null;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /**
             * Pending
             * @default false
             */
            pending: boolean;
        };
        /** ParserInfo */
        ParserInfo: {
            /** Model */
            model: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /**
         * PlatformMatch
         * @description One accepted Spotify track / YouTube video match.
         */
        PlatformMatch: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Artists */
            artists?: string[];
            /** Url */
            url: string;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /**
         * Resolution
         * @description Outcome of resolving one track/component against the platforms.
         *
         *     Precision over recall: a platform field is populated ONLY when the match
         *     cleared the confidence threshold. Empty fields on bootlegs/edits are the
         *     correct outcome, not a failure ("no_match"). A null Resolution slot on a
         *     track means resolution was never attempted.
         */
        Resolution: {
            /**
             * Status
             * @enum {string}
             */
            status: "resolved" | "partial" | "no_match" | "unreleased";
            /** Track Id */
            track_id?: string | null;
            spotify?: components["schemas"]["PlatformMatch"] | null;
            youtube?: components["schemas"]["PlatformMatch"] | null;
            lastfm?: components["schemas"]["LastfmMatch"] | null;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Method
             * @default batch_llm
             * @enum {string}
             */
            method: "batch_llm" | "registry" | "skip" | "cascade" | "agent";
            /** Resolved At */
            resolved_at?: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * Setlist
         * @description The persisted setlist record (future `Setlists` + `Setlist_Tracks` rows).
         */
        Setlist: {
            /** Id */
            id?: string;
            /**
             * Source
             * @default 1001tracklists
             */
            source: string;
            /** Source Url */
            source_url: string;
            /** Title */
            title?: string | null;
            /** Dj Names */
            dj_names?: string[];
            /** Event */
            event?: string | null;
            /** Date Recorded */
            date_recorded?: string | null;
            /** Genres */
            genres?: string[];
            /** Media Url */
            media_url?: string | null;
            /** Media Kind */
            media_kind?: string | null;
            /** Scraped At */
            scraped_at?: string;
            parser: components["schemas"]["ParserInfo"];
            /** Tracks */
            tracks?: components["schemas"]["SetlistTrack"][];
        };
        /**
         * SetlistDetail
         * @description Full setlist plus its resolution lifecycle metadata.
         */
        SetlistDetail: {
            setlist: components["schemas"]["Setlist"];
            /** Status */
            status: string;
            /** Coverage */
            coverage: {
                [key: string]: unknown;
            } | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Created At */
            created_at: string | null;
        };
        /**
         * SetlistSummary
         * @description Lightweight browse-card row.
         */
        SetlistSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** Dj Names */
            dj_names: string[];
            /** Event */
            event: string | null;
            /** Date Recorded */
            date_recorded: string | null;
            /** Genres */
            genres: string[];
            /** Media Url */
            media_url: string | null;
            /** Track Count */
            track_count: number;
            /** Status */
            status: string;
            /** Coverage */
            coverage: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string | null;
        };
        /**
         * SetlistTrack
         * @description A parsed track plus scrape context and the (future) resolution slot.
         */
        SetlistTrack: {
            /**
             * Position
             * @description Track position, echoed from the input row
             */
            position: number;
            /**
             * Raw Text
             * @description The input raw_text echoed back VERBATIM
             */
            raw_text: string;
            /**
             * Artists
             * @description Artist names split out (e.g. 'A & B' -> ['A', 'B']). Empty for ID tracks.
             */
            artists?: string[];
            /**
             * Title
             * @description Track title without remix/version suffix. None for ID tracks.
             */
            title?: string | null;
            /**
             * Remix
             * @description Remix/version/edit descriptor, e.g. 'Extended Mix', 'Fred again.. Remix'
             */
            remix?: string | null;
            /**
             * Is Id
             * @description True if the track is unreleased/unidentified ('ID - ID' or artist ID)
             * @default false
             */
            is_id: boolean;
            /**
             * Played With
             * @description Position of the track this row is layered over ('w/' rows), else null
             */
            played_with?: number | null;
            /**
             * Mashup Components
             * @description For mashups ('A vs. B'), the component tracks; empty otherwise
             */
            mashup_components?: components["schemas"]["MashupComponent"][];
            /** Source Track Number */
            source_track_number?: number | null;
            /** Cue Time */
            cue_time?: string | null;
            resolution?: components["schemas"]["Resolution"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WindowSet
         * @description Every window for a setlist, plus what the caller may do with them.
         */
        WindowSet: {
            /** Setlist Id */
            setlist_id: string;
            /**
             * Timing
             * @enum {string}
             */
            timing: "cue" | "estimated";
            /** Live Capable */
            live_capable: boolean;
            /** Duration S */
            duration_s: number;
            /** Windows */
            windows: components["schemas"]["CueWindow"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ds_session?: string | null;
                ds_pending?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lastfm_start_auth_lastfm_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    lastfm_callback_auth_lastfm_callback_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                ds_pending?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lastfm_complete_auth_lastfm_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ds_pending?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_setlists_setlists_get: {
        parameters: {
            query?: {
                q?: string | null;
                dj?: string | null;
                genre?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetlistSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_setlist_setlists__setlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setlist_cues_setlists__setlist_id__cues_get: {
        parameters: {
            query?: {
                /** @description Recording length in seconds, when known */
                duration?: number | null;
            };
            header?: never;
            path: {
                setlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindowSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_preview_setlists__setlist_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
